# Generated by Django 4.1.4 on 2023-01-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_proyecto_options_alter_proyecto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Hiperevínculo'),
        ),
    ]
